# Generated by Django 5.1.5 on 2025-02-24 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Correspondencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('referencia', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('paginas', models.IntegerField()),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], max_length=20)),
                ('estado', models.CharField(max_length=50)),
                ('personal_destinatario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.personal')),
                ('remitente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.cliente')),
                ('tipo_documento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='correspondencia.tipodocumento')),
            ],
        ),
        migrations.CreateModel(
            name='CorrespondenciaEntrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_registro', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('correspondencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrantes', to='correspondencia.correspondencia')),
            ],
        ),
        migrations.CreateModel(
            name='CorrespondenciaSaliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cite', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_hora_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_hora_confirmacion_recepcion', models.DateTimeField(blank=True, null=True)),
                ('fecha_proximo_seguimiento', models.DateTimeField(blank=True, null=True)),
                ('correspondencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saliente', to='correspondencia.correspondencia')),
            ],
        ),
        migrations.CreateModel(
            name='FlujoAprobacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_revision', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='Pendiente', max_length=50)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('correspondencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flujos_aprobacion', to='correspondencia.correspondencia')),
                ('revisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.personal')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('fecha_notificacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=50)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='usuarios.personal')),
            ],
        ),
    ]
