# Generated by Django 5.1.5 on 2025-03-30 03:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('documento', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correspondencia',
            fields=[
                ('id_correspondencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('referencia', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('paginas', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], max_length=20)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('en_revision', 'En revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='en_revision', max_length=20)),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correspondencias_relacionadas', to='documento.documento')),
                ('personal_destinatario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.personal')),
                ('remitente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.cliente')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id_tipo_documento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumentoInterno',
            fields=[
                ('id_tipo_documento_interno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CorrespondenciaEntrante',
            fields=[
                ('correspondencia_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='correspondencia.correspondencia')),
                ('id_correspondencia_entrante', models.AutoField(primary_key=True, serialize=False)),
                ('nro_registro', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
            ],
            bases=('correspondencia.correspondencia',),
        ),
        migrations.CreateModel(
            name='CorrespondenciaSaliente',
            fields=[
                ('correspondencia_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='correspondencia.correspondencia')),
                ('id_correspondencia_saliente', models.AutoField(primary_key=True, serialize=False)),
                ('cite', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True)),
                ('fecha_seguimiento', models.DateTimeField(blank=True, null=True)),
                ('archivo_word', models.FileField(blank=True, null=True, upload_to='documentos_borrador/')),
            ],
            bases=('correspondencia.correspondencia',),
        ),
        migrations.CreateModel(
            name='FlujoAprobacion',
            fields=[
                ('id_flujo_aprobacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_revision', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='Pendiente', max_length=50)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('correspondencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flujos_aprobacion', to='correspondencia.correspondencia')),
                ('revisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.personal')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.TextField()),
                ('fecha_notificacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=50)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='usuarios.personal')),
            ],
        ),
        migrations.CreateModel(
            name='CorrespondenciaInterna',
            fields=[
                ('id_correspondencia_interna', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.PositiveIntegerField(editable=False)),
                ('gestion', models.PositiveIntegerField(default=2025, editable=False)),
                ('cite', models.CharField(blank=True, max_length=100, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('contenido', models.TextField()),
                ('personal_destinatario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.personal')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='correspondencia.tipodocumentointerno')),
            ],
            options={
                'unique_together': {('tipo', 'numero', 'gestion')},
            },
        ),
    ]
