# Generated by Django 5.1.5 on 2025-02-24 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0001_initial'),
        ('documento', '0002_remove_documento_correspondencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondencia',
            name='documento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correspondencias_relacionadas', to='documento.documento'),
        ),
    ]
