# Generated by Django 5.1.5 on 2025-03-17 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0002_alter_correspondencia_paginas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondencia',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
