# Generated by Django 5.1.5 on 2025-02-24 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0003_alter_correspondenciaentrante_correspondencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondenciaentrante',
            name='correspondencia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrantes', to='correspondencia.correspondencia'),
        ),
    ]
