# Generated by Django 5.1.5 on 2025-03-18 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0003_alter_correspondencia_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondencia',
            name='estado',
            field=models.CharField(choices=[('en_revision', 'En revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='en_revision', max_length=20),
        ),
    ]
