# Generated by Django 5.1.5 on 2025-03-18 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0004_alter_correspondencia_estado'),
        ('documento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondencia',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correspondencias_relacionadas', to='documento.documento'),
        ),
    ]
