# Generated by Django 5.1.5 on 2025-02-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0004_alter_correspondenciaentrante_correspondencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodocumento',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
