# Generated by Django 5.1.5 on 2025-03-20 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0006_alter_correspondencia_estado'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumentoInterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CorrespondenciaInterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('gestion', models.PositiveIntegerField(default=2025)),
                ('codigo', models.CharField(blank=True, max_length=100, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('contenido', models.TextField()),
                ('personal_destinatario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.personal')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='correspondencia.tipodocumentointerno')),
            ],
            options={
                'unique_together': {('tipo', 'numero', 'gestion')},
            },
        ),
    ]
