# Generated by Django 5.1.5 on 2025-03-20 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0007_tipodocumentointerno_correspondenciainterna'),
    ]

    operations = [
        migrations.RenameField(
            model_name='correspondenciainterna',
            old_name='codigo',
            new_name='cite',
        ),
        migrations.AlterField(
            model_name='correspondenciainterna',
            name='gestion',
            field=models.PositiveIntegerField(default=2025, editable=False),
        ),
        migrations.AlterField(
            model_name='correspondenciainterna',
            name='numero',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
