# Generated by Django 5.1.5 on 2025-03-21 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0009_delete_contadorregistroentrante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correspondenciaentrante',
            name='ultimo_registro',
        ),
    ]
