# Generated by Django 5.1.5 on 2025-03-02 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0009_alter_correspondenciaentrante_nro_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondenciaentrante',
            name='nro_registro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
