# Generated by Django 5.1.5 on 2025-03-21 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0010_remove_correspondenciaentrante_ultimo_registro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContadorCiteSaliente',
        ),
        migrations.AddField(
            model_name='correspondenciasaliente',
            name='ultimo_cite',
            field=models.IntegerField(default=0),
        ),
    ]
