# Generated by Django 5.1.5 on 2025-03-21 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0011_delete_contadorcitesaliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correspondenciasaliente',
            name='ultimo_cite',
        ),
    ]
