# Generated by Django 5.1.5 on 2025-03-11 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0011_remove_correspondencia_tipo_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContadorRegistroEntrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_registro', models.IntegerField(default=0)),
            ],
        ),
    ]
