# Generated by Django 5.1.5 on 2025-03-11 22:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0012_contadorregistroentrante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondencia',
            name='paginas',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
