# Generated by Django 5.1.5 on 2025-03-11 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0013_alter_correspondencia_paginas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContadorCiteSaliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_cite', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='correspondenciasaliente',
            old_name='fecha_hora_confirmacion_recepcion',
            new_name='fecha_envio',
        ),
        migrations.RenameField(
            model_name='correspondenciasaliente',
            old_name='fecha_hora_envio',
            new_name='fecha_recepcion',
        ),
        migrations.RenameField(
            model_name='correspondenciasaliente',
            old_name='fecha_proximo_seguimiento',
            new_name='fecha_seguimiento',
        ),
    ]
