# Generated by Django 5.1.5 on 2025-03-11 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0014_contadorcitesaliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondenciasaliente',
            name='archivo_word',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
        migrations.AddField(
            model_name='correspondenciasaliente',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('revision', 'En revisión'), ('enviado', 'Enviado')], default='borrador', max_length=20),
        ),
    ]
