# Generated by Django 5.1.5 on 2025-03-12 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0015_correspondenciasaliente_archivo_word_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correspondenciasaliente',
            name='archivo_word',
        ),
    ]
