# Generated by Django 5.1.5 on 2025-03-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0016_remove_correspondenciasaliente_archivo_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondenciasaliente',
            name='archivo_word',
            field=models.FileField(blank=True, null=True, upload_to='documentos_borrador/'),
        ),
    ]
