# Generated by Django 5.1.5 on 2025-03-15 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0018_descargadocumento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correspondenciasaliente',
            name='correspondencia',
        ),
    ]
