# Generated by Django 5.1.5 on 2025-03-17 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='ruta_archivo')),
                ('tipo', models.CharField(choices=[('enviado', 'Enviado'), ('recibido', 'Recibido')], max_length=10)),
                ('nombre_archivo', models.CharField(blank=True, max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('tamano_archivo', models.IntegerField()),
                ('contenido_extraido', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContenidoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_procesamiento', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=50)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documento.documento')),
            ],
        ),
    ]
