# Generated by Django 5.1.5 on 2025-02-24 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('correspondencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='documentos/')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('tipo_archivo', models.CharField(max_length=50)),
                ('tamano_archivo', models.IntegerField()),
                ('contenido_extraido', models.TextField(blank=True, null=True)),
                ('correspondencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_relacionados', to='correspondencia.correspondencia')),
            ],
        ),
        migrations.CreateModel(
            name='ContenidoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_procesamiento', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=50)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documento.documento')),
            ],
        ),
    ]
