# Generated by Django 5.1.5 on 2025-02-24 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='correspondencia',
        ),
    ]
