# Generated by Django 5.1.5 on 2025-03-23 03:38

import documento.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(upload_to=documento.models.ruta_archivo),
        ),
    ]
