# Generated by Django 5.1.5 on 2025-03-02 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0002_remove_documento_correspondencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='nombre_archivo',
            new_name='nro_regitro_documento',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='tipo_archivo',
        ),
    ]
