# Generated by Django 5.1.5 on 2025-03-02 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0003_rename_nombre_archivo_documento_nro_regitro_documento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='nro_regitro_documento',
            new_name='nombre_archivo',
        ),
    ]
