# Generated by Django 5.1.5 on 2025-03-09 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0004_rename_nro_regitro_documento_documento_nombre_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='nombre_archivo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
