# Generated by Django 5.1.5 on 2025-03-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0005_alter_documento_nombre_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('enviado', 'Enviado'), ('remitido', 'remitido')], default='default', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(upload_to='ruta_archivo'),
        ),
    ]
