# Generated by Django 5.1.5 on 2025-03-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0006_documento_tipo_alter_documento_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('enviado', 'Enviado'), ('recibido', 'Recibido')], max_length=10),
        ),
    ]
