# Generated by Django 5.1.5 on 2025-02-22 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('correspondencia', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_plantilla', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas', to='correspondencia.tipodocumento')),
            ],
        ),
    ]
