# Generated by Django 5.1.5 on 2025-03-30 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('correspondencia', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id_plantilla', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='correspondencia.tipodocumento')),
            ],
        ),
    ]
