# Generated by Django 5.1.5 on 2025-03-13 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0018_descargadocumento'),
        ('plantilla', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantilla',
            old_name='nombre_plantilla',
            new_name='nombre',
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='correspondencia.tipodocumento'),
        ),
    ]
