# Generated by Django 5.1.5 on 2025-03-31 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institucion',
            old_name='nombre',
            new_name='nombre_institucion',
        ),
    ]
