# Generated by Django 5.1.5 on 2025-04-01 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia', '0002_alter_correspondencia_personal_destinatario_and_more'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='fecha_registro',
        ),
        migrations.DeleteModel(
            name='Personal',
        ),
    ]
