# Generated by Django 5.1.5 on 2025-01-27 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosRemitente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('institucion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Directorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroRecibido',
            fields=[
                ('idrecibido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('referencia', models.CharField(max_length=100)),
                ('fojas', models.IntegerField()),
                ('adjunto', models.FileField(upload_to='adjunto/')),
                ('detalle', models.TextField()),
                ('entregado', models.BooleanField(default=False)),
                ('destinatario', models.EmailField(max_length=254)),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.datosremitente')),
            ],
        ),
    ]
