# Generated by Django 5.1.5 on 2025-02-04 23:37

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrorecibido',
            old_name='entregado',
            new_name='estadoEntrega',
        ),
        migrations.RemoveField(
            model_name='registrorecibido',
            name='destinatario',
        ),
        migrations.AddField(
            model_name='registrorecibido',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrorecibido',
            name='destinatarios',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrorecibido',
            name='estadoLectura',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registrorecibido',
            name='fechaLimite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrorecibido',
            name='prioridad',
            field=models.CharField(choices=[('Alta', 'Alta'), ('Normal', 'Normal'), ('Baja', 'Baja')], default='Normal', max_length=10),
        ),
        migrations.AddField(
            model_name='registrorecibido',
            name='tipoDocumento',
            field=models.CharField(choices=[('Informe', 'Informe'), ('Contrato', 'Contrato'), ('Memorándum', 'Memorándum')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
